### ISSUE TITLE
Error while installing microbiomeSeq

### ISSUE THREAD

**Issue by Gian77** [umerijaz/microbiomeSeq#1]
Hello,
I wanted to try microbiomeSeq, but I ended up with the following `namesapceExport` error during installation:

>Error: package or namespace load failed for ‘microbiomeSeq’ in namespaceExport(ns, exports):
 >undefined exports: differential_expression, kruskal_expression
Error: loading failed
Execution halted
ERROR: loading failed
>* removing ‘/home/gian/R/x86_64-pc-linux-gnu-library/3.4/microbiomeSeq’
Installation failed: Command failed (1)

This is my sessionInfo()
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

>Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

>locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8    
 [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8   
 [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

>attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

>other attached packages:
[1] BiocInstaller_1.26.1 devtools_1.13.3     

>loaded via a namespace (and not attached):
 [1] httr_1.3.1     compiler_3.4.1 R6_2.2.2       tools_3.4.1    withr_2.0.0   
 [6] curl_2.8.1     memoise_1.1.0  git2r_0.19.0   digest_0.6.12  tcltk_3.4.1   
> 

Thank you,
Gian

**Comment by susheelbhanu** [comment]
Agree with Gian77. I'm seeing the same issue. Is there a stable version we can download and install?

**Comment by umerijaz** [comment]
Dear both, we are currently trying to fix the installation errors. Please allow us a bit of time to test the package properly. Best Wishes, Umer

**Comment by AlfredUg** [comment]
Dear Gian and susheelbhanu, the stable version will be availed as pointed out by Umer. Please kindly bear with us. I would also want to point out an error reported on another platform.
`1. Error: package or namespace load failed for microbiomeSeq in dyn.load(file, DLLpath = DLLpath, ...):maximal number of DLLs reached ...`
To fix this error, there is need to increase the maximum number of DLLs which can be done by editing the ".Renviron" in the home directory the system, one may consider creating one if it does not exist. For example , adding these two lines in .Renviron increases the maximum number of DLLs to 1000.
`Variable name=R_MAX_NUM_DLL`
 `Value=1000`

**Comment by susheelbhanu** [comment]
Thanks Umer.

I’ll edit the .Renviron as suggested.

Best,
Susheel

**Comment by lplaisance** [comment]
Hello all, I am running into a similar problem than described above, but increasing the maximum number of DLLs by creating an .Renviron file in my home directory doesn't do the trick. Now, I am very new to Rstudio and it is very possible I didn't set up the file correctly. I went to RStudio/File/New File/Text File and paste the text above and saved it as .Renviron in the default working directory set in my preferences. But I still get the following message:

Error: package or namespace load failed for ‘microbiomeSeq’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/multtest/libs/multtest.so':
  `maximal number of DLLs reached...
In addition: Warning message:
replacing previous import ‘igraph::diversity’ by ‘phangorn::diversity’ when loading ‘microbiomeSeq’ 

I have tried restarting RStudio and the readRenviron(".Renviron") command. I am on MacOS. Any suggestion on what I should be doing differently to make this work?

Thank you,

Lilly

**Comment by AlfredUg** [comment]
Hello lpaisance,

I am hoping that your default working directory is the home directory. I suggest you use `R_MAX_NUM_DLLS=150` (just this one line) instead of the above example. For `microbiomeSeq` in particular, this should be enough. The reason as to the previous example did not work for you could be that your machine is restricted to maximum number of DLLs less than 1000. 
Please remember to restart Rstudio thereafter.

I hope that helps with the installation.

Alfred.

**Comment by rizbak** [comment]
Hi AlfredUg .

i have same problem with Gian77 .

unable to load shared object '/usr/lib64/R/modules//lapack.so':
  `maximal number of DLLs reached...
Warning: Error in chol2inv: LAPACK routines cannot be loaded

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.4.3

i will to edit Variable name=R_MAX_NUM_DLLS in ".Renviron" but I did not find directory of ".Renviron".
im used Centos 7.
Thanks..

**Comment by AlfredUg** [comment]
@rizbak, I suggest you create the ".Renviron" file because it seems the system does not have one ;
To achieve that, open the terminal (this should open in your home directory, if not, then navigate to your home directory) and do the following;

- type  `nano .Renviron`
- In the screen that appears, type `R_MAX_NUM_DLLS=150`
- Press `Ctrl + O`  followed by `return`
- Press `Ctrl + X` followed by `return`
- Close terminal and Rstudio (if you are using it). 
- Restart Rstudio and install the package.

I hope that helps,

Thanks.

**Comment by Espinosa-Gongora** [comment]
Also installation problems, but with a different error:

`library(devtools) 
install_github("umerijaz/microbiomeSeq")

Downloading GitHub repo umerijaz/microbiomeSeq@master
from URL https://api.github.com/repos/umerijaz/microbiomeSeq/zipball/master
Installing microbiomeSeq
"C:/PROGRA~1/R/R-34~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/znx422/AppData/Local/Temp/RtmpAJevI6/devtools169c2ae11a6f/umerijaz-microbiomeSeq-ce63464"  \
  --library="C:/Users/znx422/Documents/R/win-library/3.4" --install-tests 

ERROR: dependencies 'DESeq2', 'phyloseq' are not available for package 'microbiomeSeq'
* removing 'C:/Users/znx422/Documents/R/win-library/3.4/microbiomeSeq'
In R CMD INSTALL
Installation failed: Command failed (1)`

Tried to install DESeq2 separately:
`source("https://bioconductor.org/biocLite.R")
biocLite("DESeq2")`
And got more problems with installation of packages, e.g.:

`In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/stringi_1.1.6.zip': HTTP status was '404 Not Found'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘stringi’ failed`

Tried to install one of those and got more problems:
`install.packages("stringi")
Installing package into ‘C:/Users/znx422/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
        binary source needs_compilation
stringi  1.1.6  1.1.7              TRUE

  Binaries will be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/stringi_1.1.6.zip'
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/stringi_1.1.6.zip': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/stringi_1.1.6.zip'
Warning in install.packages :
  download of package ‘stringi’ failed`

These are packages I used to work with, but just got a new computer at work. I think I am going down the rabbit hole :-) 

Someone can help?

`R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Danish_Denmark.1252  LC_CTYPE=Danish_Denmark.1252    LC_MONETARY=Danish_Denmark.1252
[4] LC_NUMERIC=C                    LC_TIME=Danish_Denmark.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.13.5      BiocInstaller_1.24.0 ggplot2_2.2.1        sandwich_2.4-0       lme4_1.1-15         
[6] Matrix_1.2-12        readxl_1.0.0        

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.15     splines_3.4.3    MASS_7.3-47      munsell_0.4.3    colorspace_1.3-2 lattice_0.20-35 
 [7] R6_2.2.2         rlang_0.2.0      minqa_1.2.4      httr_1.3.1       plyr_1.8.4       tools_3.4.3     
[13] grid_3.4.3       gtable_0.2.0     nlme_3.1-131     git2r_0.21.0     withr_2.1.1      digest_0.6.15   
[19] lazyeval_0.2.1   tibble_1.4.2     nloptr_1.0.4     curl_3.1         memoise_1.1.0    compiler_3.4.3  
[25] pillar_1.2.1     cellranger_1.1.0 scales_0.5.0     zoo_1.8-1 `

Many thanks :-)

**Comment by rizbak** [comment]
Thanks for your suggest. My apps was worked..

Pada tanggal Jum, 2 Feb 2018 23.48, Alfred Ssekagiri <
notifications@github.com> menulis:

**Comment by siobhon-egan** [comment]
Just wondering if this has been solved?
I am running into the same issue.

RStudio output
`> install_github("umerijaz/microbiomeSeq")
Downloading GitHub repo umerijaz/microbiomeSeq@master
from URL https://api.github.com/repos/umerijaz/microbiomeSeq/zipball/master
Installing microbiomeSeq
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/c1/1wk2dj0s543fp9k7jh695ndw0000gn/T/Rtmp0S2TJ6/devtools6df368361daa/umerijaz-microbiomeSeq-ce63464'  \
  --library='/Library/Frameworks/R.framework/Versions/3.5/Resources/library' --install-tests 

ERROR: dependency ‘DESeq2’ is not available for package ‘microbiomeSeq’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/microbiomeSeq’
Installation failed: Command failed (1)`

**Comment by AlfredUg** [comment]
Heya @siobhon-egan 

Your issue is due to a missing dependancy "DESeq2", 
`ERROR: dependency ‘DESeq2’ is not available for package ‘microbiomeSeq’` .
Please just make sure you have all the dependancies available, see full list [here](https://github.com/umerijaz/microbiomeSeq/blob/master/DESCRIPTION). 

I hope that helps.

Alfred.

**Comment by nhungdoan1905** [comment]
hi, I was try to install microbiomeSeq packages, and what problems I got:

Installing 15 packages: DESeq2, KMDA, WGCNA, fso, randomForest, genefilter, locfit, geneplotter, RcppArmadillo, fastcluster, GO.db, labdsv, annotate, XML, Rtsne
Error: Failed to install 'microbiomeSeq' from GitHub:
  (converted from warning) unable to access index for repository https://www.stats.ox.ac.uk/pub/RWin/bin/macosx/el-capitan/contrib/3.5:
  cannot open URL 'https://www.stats.ox.ac.uk/pub/RWin/bin/macosx/el-capitan/contrib/3.5/PACKAGES'
> install.packages('microbiomeSeq', dependencies=TRUE, repos='http://cran.rstudio.com/')
Warning in install.packages :
  package ‘microbiomeSeq’ is not available (for R version 3.5.0)
how can I fix this
