### ISSUE TITLE
Installation failed due to missing dependency (WGCNA) 

### ISSUE THREAD

**Issue by DSLUCB** [umerijaz/microbiomeSeq#10]
I am running R v.3.4.3. The error is about the "WGCNA" package not being available for microbiomeSeq.

"ERROR: dependency ‘WGCNA’ is not available for package ‘microbiomeSeq’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/microbiomeSeq’
Installation failed: Command failed (1)"

Any advice on how to solve this? 

Thanks.

**Comment by AlfredUg** [comment]
Hey @DSLUCB, please install "WGCNA" package from Cran [https://cran.r-project.org/web/packages/WGCNA/index.html](https://cran.r-project.org/web/packages/WGCNA/index.html), alternatively, if you are using Rstudio you can directly install it using the install button on the packages tab.

**Comment by DSLUCB** [comment]
Hi @AlfredUg , I tried to do that too but it may need compilation from source.
"Package which is only available in source form, and may need compilation of
  C/C++/Fortran: ‘WGCNA’
Do you want to attempt to install these from sources? "

I will try this if it is not too hard but microbiomeSeq's functions look great and worst case is to run independently those that do not rely on WGCNA.

Thank you and very good work!

**Comment by AlfredUg** [comment]
Hi @DSLUCB, you could follow the procedure [here](https://labs.genetics.ucla.edu/horvath/CoexpressionNetwork/Rpackages/WGCNA/InstallationInstructions.html) see if it gets you to install WGCNA successfully.
It is not hard, following those instructions may solve this issue really fast.
Please kindly let us know how it goes.

Thanks.

**Comment by motroy** [comment]
Hi all,

If it helps, I am using R version 3.4.3 (on ubuntu 14.04), also had a problem with WGCNA...then installed it through bioconductor, and it works.

> source("http://bioconductor.org/biocLite.R")
> biocLite('WGCNA')

then retry the microbiomeSeq installation

regards

**Comment by rolo1323** [comment]
I am having the same issue trying to install WGCNA. I tried installing directly from Cran and bioconductor to no avail. 

"Warning: package ‘fastcluster’ was built under R version 3.4.4
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘mvtnorm’
ERROR: lazy loading failed for package ‘WGCNA’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/WGCNA’
installation of package ‘WGCNA’ had non-zero exit status"

Any help would be greatly appreciated. 

Thanks.

**Comment by AlfredUg** [comment]
Heya @rolo1323, from the error message above, `there is no package called ‘mvtnorm’`, install  `mvtnorm` normally from cran and you will be good to go.

I hope that helps.

**Comment by rolo1323** [comment]
It did! Thanks.
