### ISSUE TITLE
SGA Analysis

### ISSUE THREAD

**Issue by KIRANBHATIA145** [umerijaz/microbiomeSeq#17]
Hi,

I am trying to run the following script:

library (foreign)
SGA <- read.dta("U:/Kiran Bhatia/LG_ANALYSIS_101012017/LG_DATA/monitoring ana/SGA_data1.dta")
library(hbgd)
SGA$percentile_weight <- igb_wtkg2centile(SGA$ga, SGA$weight, sex=SGA$sex1)

and getting the error:

SGA$percentile_weight <- igb_wtkg2centile(SGA$GA, SGA$Weight, sex = SGA$Sex)
Error in data.frame(x = gagebrth, y = val, var = var, sex = sex, stringsAsFactors = FALSE) :
arguments imply differing number of rows: 0, 1

Beginners in R, don't know much about R coding. Please help to resolve my issue.

Thanks.
Kiran Bhatia
India

**Comment by AlfredUg** [comment]
@KIRANBHATIA145, 
Kindly refer to this [this](hafen.github.io/docs-hbgd/rd.html), it might be of help.
