### ISSUE TITLE
plot_anova_diversity doesn't work

### ISSUE THREAD

**Issue by giriarteS** [umerijaz/microbiomeSeq#2]
I am getting the following error.:

p<-plot_anova_diversity(ps, method = c("richness", "simpson"), grouping_column =  "sample_type", pValueCutoff = 0.05)

Error in .subset(x, j) : invalid subscript type 'list'
5. `[.data.frame`(x, i, j)
4. `[.data.table`(dt, , list(pvalue = sprintf("%.2g", tryCatch(summary(aov(value ~ .group.))[[1]][["Pr(>F)"]][1], error = function(e) NULL))), by = list(measure))
3. dt[, list(pvalue = sprintf("%.2g", tryCatch(summary(aov(value ~ .group.))[[1]][["Pr(>F)"]][1], error = function(e) NULL))), by = list(measure)]
2. perform_anova(df, meta_table, grouping_column, pValueCutoff)
1. plot_anova_diversity(ps, method = c("richness", "simpson"), grouping_column = "comp", pValueCutoff = 0.05)

All the other function run fine, but this want doesn't.

**Comment by AlfredUg** [comment]
@giriarteS , Thank you for raising this here, the issue has been fixed, it should work well now.

**Comment by giriarteS** [comment]
I am still getting the same error.

**Comment by giriarteS** [comment]
Now its working!! Thanks

**Comment by AlfredUg** [comment]
@giriarteS , That sounds great, I will close this issue then.
