### ISSUE TITLE
plot_taxa change Taxa names

### ISSUE THREAD

**Issue by AlexGaithuma** [umerijaz/microbiomeSeq#23]
Hello,
I am plotting beta diversity with:
plot_taxa(ps3, grouping_column = "Sex", method = "hellinger", number.taxa = 21, 
               filename = NULL)

I get the plot but my taxa names are OTU names not bacteria names.
![image](https://user-images.githubusercontent.com/19816817/50811600-7bfdfe00-1352-11e9-929f-c69e59b69ed9.png)

How do I change this?

**Comment by AlfredUg** [comment]
Hey @AlexGaithuma, 
You may want to use the `taxa_level` function to have information at a given taxonomic rank. For example to have taxa at Family level, 

`ps_fam <- taxa_level(ps3, which_level = "Family")`

Then produce a plot with taxa names at this taxonomic rank using the `plot_taxa` function.

`plot_taxa(ps_fam, grouping_column = "Sex", method = "hellinger", number.taxa = 21,
filename = NULL)`

Hope that helps,
Alfred..

**Comment by AlexGaithuma** [comment]
> Hey @AlexGaithuma,
> You may want to use the `taxa_level` function to have information at a given taxonomic rank. For example to have taxa at Family level,
> 
> `ps_fam <- taxa_level(ps3, which_level = "Family")`
> 
> Then produce a plot with taxa names at this taxonomic rank using the `plot_taxa` function.
> 
> `plot_taxa(ps_fam, grouping_column = "Sex", method = "hellinger", number.taxa = 21, filename = NULL)`
> 
> Hope that helps,
> Alfred..

Thanks much@AlfredUg,
It worked!
![image](https://user-images.githubusercontent.com/19816817/50816074-c9826700-1362-11e9-9080-a5f3790d0d1e.png)
