### ISSUE TITLE
object not found

### ISSUE THREAD

**Issue by sravyapagadala1** [umerijaz/microbiomeSeq#24]
Hi ,

I could install the package "microbiomeSeq" with its dependencies successfully.
For the next step to Generate a phyloseq object i have encountered the following : 

> OTU = otu_table(as.matrix(abund_table), taxa_are_rows = FALSE)
Error in as.matrix(abund_table) : object 'abund_table' not found
> TAX = tax_table(as.matrix(OTU_taxonomy))
Error in as.matrix(OTU_taxonomy) : object 'OTU_taxonomy' not found
> SAM = sample_data(meta_table)
Error in sample_data(meta_table) : object 'meta_table' not found

PS: I could find components of the data, print out the data to find out the structure.Output inline for the same:
> print(pitlatrine)
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 8883 taxa and 81 samples ]
sample_data() Sample Data:       [ 81 samples by 14 sample variables ]
tax_table()   Taxonomy Table:    [ 8883 taxa by 6 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 8883 tips and 8881 internal nodes ]

Can someone help me how these objects are formed?

**Comment by sravyapagadala1** [comment]
Hi @AlfredUg 

Thank you for your response.
But i see its a "pretend taxonomy table" , what is the file used in this repo to create a OTU_taxonomy table?

**Comment by AlfredUg** [comment]
The file used to create the otu_taxonomy table is [here](http://userweb.eng.gla.ac.uk/umer.ijaz/bioinformatics/ecological/All_Good_P2_C03_Taxonomy.csv)

**Comment by sravyapagadala1** [comment]
Hi @AlfredUg 

Thank you for your reply!
