### ISSUE TITLE
ordination Error - “veg_distance” not available for .C() for package “vegan”

### ISSUE THREAD

**Issue by giriarteS** [umerijaz/microbiomeSeq#28]
I am getting the following error with the ordination function:
`ord.res <- ordination(psN, which_distance = "bray", method = "NMDS",grouping_column = "Treatment", pvalue.cutoff=0.05)`

`Error in .C("veg_distance", x = as.double(x), nr = N, nc = ncol(x), d = double(N * : "veg_distance" not available for .C() for package "vegan"`

Below are the package versions:

`R version 3.4.1 (2017-06-30)`
`Platform: x86_64-apple-darwin15.6.0 (64-bit)`
`Running under: macOS High Sierra 10.13.6`

`packageVersion('microbiomeSeq')`
`packageVersion('phyloseq')`
`packageVersion('vegan')`

`[1] ‘0.1’`
`[1] ‘1.22.3’`
`[1] ‘2.5.4’`

Thanks

**Comment by AlfredUg** [comment]
Heya @giriarteS, 

This  issue is about the conflicts between `phyloseq` and `vegan`.  The common work around is re-installing phyloseq from source.
```
library("devtools")
install_github("joey711/phyloseq")
```
You can follow the discussion about this [here](https://github.com/joey711/phyloseq/issues/921).

Hope that helps.

**Comment by giriarteS** [comment]
Thanks!!!
