### ISSUE TITLE
Error in cor() from co_occurence_network()

### ISSUE THREAD

**Issue by GeoMicroSoares** [umerijaz/microbiomeSeq#4]
Hello again,

Sorry to bother, but here's something else that's not running properly using co_occurence_network(). Funnily enough, I can replicate it properly from your tutorial but it doesn't work with my data:

```
> data(pitlatrine)
> physeq <- pitlatrine
> co_occr <- co_occurence_network(physeq, grouping_column = "Country", 
rhos = 0.35, select.condition = "V", scale.vertex.size=3, scale.edge.width=15)
```
```
> str(co_occr, max.level = 1)
List of 3
 $ net       :List of 3
 $ comm_data : num [1:81, 1:8883] 0 0 0 0 0 0 0 0 0 0 ...
  ..- attr(*, "dimnames")=List of 2
 $ meta_table:'data.frame':	52 obs. of  15 variables:
```
Now with my dataset:
```
co_occr <- co_occurence_network(ps, grouping_column = "Geology", rhos = 0.35, select.condition = "V", scale.vertex.size=3, scale.edge.width=15)
Error in cor(x, y, use = use, ...) : 'x' has a zero dimension.
```
Have no idea why this is going on. Everything is properly installed from what I check for example...

Some quick data on my dataset, which has a read count distribution similar to pitlatrine:
```
> ps
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 2207 taxa and 70 samples ]
sample_data() Sample Data:       [ 70 samples by 16 sample variables ]
tax_table()   Taxonomy Table:    [ 2207 taxa by 7 taxonomic ranks ]
> plot(sort(taxa_sums(ps)) , ylab="Total reads", xlab="OTUs")
```
![image](https://user-images.githubusercontent.com/14272488/34907948-09ab0756-f87f-11e7-8e45-274b0172508b.png)

**Comment by AlfredUg** [comment]
@GeoMicroSoares, Thank you for raising this issue, it is not a bother at all, we really appreciate this. The co-occurence network function best works with data at a given taxonomic rank which is actually more informative. For example, to reproduce what is in the tutorial, you may want to use the `taxa_level` function first as illustrated in the tutorial. For example,
`physeq <- taxa_level(physeq, which_level = "Genus")`

`co_occr <- co_occurence_network(physeq, grouping_column = "Country", rhos = 0.35, method="cor", qval_threshold=0.05, select.condition = "V", scale.vertex.size=4, scale.edge.width=10, plotNetwork=T, plotBetweennessEeigenvalue=F)`

I hope that helps.

**Comment by GeoMicroSoares** [comment]
Heya @AlfredUg ,
Finally managed to get back to this!
The error unfortunately continues, after I've updated the package with 
```
library(devtools)
install_github("umerijaz/microbiomeSeq") 
```

Running my stuff again: 
```
> physeq <- taxa_level(MADS_v2_p.f.noArc.es.eo, which_level = "Genus")
> co_occr <- co_occurence_network(physeq, grouping_column = "Geology", rhos = 0.35, method="cor", 
                                qval_threshold=0.05, select.condition = "V", scale.vertex.size=4, 
                                scale.edge.width=10, plotNetwork=T, plotBetweennessEeigenvalue=F)
```
I still get: ```Error in vegan::rrarefy(abund_table, min(rowSums(abund_table))) : 
  function is meaningful only for integers (counts)```

BTW, this error comes up either with a standard count table and with relative abundances!

Anything I can get you from this side that may help?

Thanks again!

**Comment by AlfredUg** [comment]
Thanks @GeoMicroSoares, 
About the issue BEFORE update, note that `select.condition` should be one of the levels of the grouping variable in this case "Geology". 
AFTER update, the function works but you do not get results, I suppose the empty data frames generated above show that no co-occurence is found at default correlation threshold. As such,  specifying the threshold correlation for co-occurence via `rhos` argument could yield some results.
