### ISSUE TITLE
ordination

### ISSUE THREAD

**Issue by marasodi** [umerijaz/microbiomeSeq#47]
Hi please assist, I ran this and I got the error below
p <- plot.ordination(ord.res, method="NMDS", pvalue.cutoff=0.05, show.pvalues=T)

ERROR:[1] groups p_value label
<0 rows> (or 0-length row.names)
Error in $<-.data.frame(*tmp*, "p_label", value = "p-value= ") :
replacement has 1 row, data has 0

please assist

**Comment by AlfredUg** [comment]
Hi @marasodi, kindly use the issue at [this](https://github.com/umerijaz/microbiomeSeq/issues/30#issuecomment-661815897) link, we are responding to it from there. I will go on close this for now.
