### ISSUE TITLE
Error in .subset(x, j) : invalid subscript type 'list'

### ISSUE THREAD

**Issue by Marieag** [umerijaz/microbiomeSeq#5]
Hi. 
Sorry to bother you, but I have encountered some issues while trying to use microbiomeSeq. 

I'm not very R-savvy, so it's more than likely that I've made a mistake, or forgotten something, but I tried running your tutorial with the pitlatrine dataset, and when inputting the first commands, I keep getting this error: 

"
> px<-plot_anova_diversity(pitlatrine, method = c("richness","simpson", "shannon"),grouping_column =  "Country",pValueCutoff=0.05)

Error in .subset(x, j) : invalid subscript type 'list'
"
A quick search tells me that I should probably transform the sample data in the phyloseq object, but I get the same result when I try to convert the sample data to a dataframe. Do you have any suggestions to how to bypass this when using an already assembled phyloseq object, such as the tutorial dataset?

Please keep up the good work, it looks like such a useful package. 
Thanks in advance, 
Yours, Marie

**Comment by AlfredUg** [comment]
@Marieag, Many thanks for raising this, I suggest you install the package again using `install_github("umerijaz/microbiomeSeq")` and use that, I have tested it and its working fine. Please kindly keep us posted. If it works fine, we shall need to close this issue. Thanks.

**Comment by Marieag** [comment]
I tried reinstalling and it works perfectly now. I must have used an older version, or made a mistake somehow. Thanks, and sorry for bothering you! 
Feel free to close/delete this topic, so it won't clog up proper issues. 
cheers, Marie

**Comment by AlfredUg** [comment]
@Marieag , I am glad its working perfectly now. Feel free to raise any issue you find while working with microbiomeSeq, we are always ready and happy to have issues fixed. Thanks.
