### ISSUE TITLE
plot_taxa() - Error in beta.div(abund_table, method = method, sqrt.D = F, samp = T, 

### ISSUE THREAD

**Issue by Marieag** [umerijaz/microbiomeSeq#6]
Hello again. 

I'm getting another issue when trying to run this command 

```
>p <- plot_taxa(physeq,grouping_column="Country", method="hellinger", number.taxa=21, filename=NULL)
Error in beta.div(abund_table, method = method, sqrt.D = F, samp = T,  : 
  could not find function "beta.div"
```

I'm running the latest stable versions of R and Rstudio, and have updated all packages, but I'm getting the issue with both my own dataset and the tutorial pitlatrine dataset. 
Any idea how to work around it? 

Thanks, 
Marie

**Comment by Marieag** [comment]
Also, sort-of-related, when I try to do co-ocurrence networks, it seems a lot of packages need to be installed for it to work (haven't gotten that far yet), would you happen to have a list of packages that is needed to run it?

**Comment by AlfredUg** [comment]
Many thanks for raising this @Marieag.
1. The function `beta.div` is part of  [adespatial](https://cran.r-project.org/web/packages/adespatial/index.html) package which you can install directly from RStudio. Once you have that installed, `plot_taxa` will work well.
2. Something else that could be useful is to first use `taxa_level` function which gives community data at a given taxonomic rank, for example, to obtain census data at Phylum level, use; `physeq<-taxa_level(pitlatrine, "Phylum")`. 
3. About the packages, you can find the full list of dependancies in the description file [here](https://github.com/umerijaz/microbiomeSeq/blob/master/DESCRIPTION). For co-ocurrence networks specifically, the required packages include: [WGCNA](https://labs.genetics.ucla.edu/horvath/CoexpressionNetwork/Rpackages/WGCNA/), [igraph](http://igraph.org/r/), [reshape2](https://cran.r-project.org/web/packages/reshape2/index.html), [vegan](https://cran.r-project.org/web/packages/vegan/index.html) and [ggplot2](https://cran.r-project.org/web/packages/ggplot2/index.html).

I hope that helps.

**Comment by Marieag** [comment]
Sorry for the late response. 
Thanks for your feedback - plot_taxa is working fine after installing adespatial, but I'm getting a persistent error when doing the co-occurence networks, 

`co_occr <- co_occurence_network(pitlatrine, grouping_column = "Country", rhos = 0.35, method="cor", 
+                                 qval_threshold=0.05, select.condition = "V", scale.vertex.size=4, scale.edge.width=10, 
+                                 plotNetwork=T, plotBetweennessEeigenvalue=F)

Error in membership(temp_comm) : could not find function "membership"` 

I get this error with the tutorial dataset as well as my own, and with or without using  `taxa_level`. 
Any ideas?

**Comment by AlfredUg** [comment]
@Marieag, `membership` function is part of the `igraph` package. Therefore, you can install igraph and load it. Thereafter, this error will not appear anymore.

**Comment by Marieag** [comment]
@AlfredUg. Strange. I had `igraph` called already. I tried deleting the `igraph` library folder, reinstalling and recalling the package when doing the co-occurence networks, and it worked afterwards. Some possible masking going on? 

I now have the network graph, but I can't seem to create the betweeness plot, when 
`plotBetweennessEeigenvalue=T`
regardless of 
`plotNetwork=F` or `plotNetwork=T`
It doesn't give me an error message, it just does not output any plots. I looked through construct_network.R - it seems to accept my object as `g1` for the network plot, but not the betweenness plot. 

I tried running the function `plot_betweenness_eigenvalue ` separately, and got the error 
`Error in igraph::betweenness(g1) : Not a graph object`. 

I suspect something is going wrong when calling the actual plot in the function? 

I'd really love to be able to make this graph, it's perfect for our data, so I hope you won't mind helping me out again. Thanks!

**Comment by AlfredUg** [comment]
@Marieag, `plotBetweennessEeigenvalue=T` produces plots of Betweenness Versus Eigen value centrality of the graph in the working directory.

**Comment by Marieag** [comment]
Hi, sorry I never got back to you - thank you so much for your help.
You're right, they're in the WD. Sorry for bothering you before checking :$

**Comment by AlfredUg** [comment]
Hi @Marieag,  am glad that works fine.

**Comment by BS2018** [comment]
Hello,
How to deal with this error while using the function co_occurence_network?

Error in vegan::rrarefy(abund_table, min(rowSums(abund_table))) : 
  object 'do_rrarefy' not found

**Comment by AlfredUg** [comment]
@BS2018, check that package vegan is loaded. This error is a result of R not finding rrarefy function.

I hope that helps.

**Comment by BS2018** [comment]
I have loaded almost everything
library(microbiomeSeq)
library(ape)
library(igraph)
library(DESeq2)
library(KMDA)
library(vegan)
library(phyloseq)
library(WGCNA)
library(fso)
library(randomForest)
library(data.table)
library(reshape2)
library(gtable)
library(ggplot2)
library(gridExtra)

Even then I get  the same error.

**Comment by BS2018** [comment]
After installing vegan again I got it. Thank you so much.

**Comment by AlfredUg** [comment]
Good stuff @BS2018
