### ISSUE TITLE
Error in env_taxa_correlation()

### ISSUE THREAD

**Issue by Razumall** [umerijaz/microbiomeSeq#7]
Hi. I'd like to execute ` env_taxa_correlation() `, but failed. Other function ( e.g. plot_anova_diversity, plot_anova_diversity ) are doing well. Is there any solution? Attached my code below. 

```
data(pitlatrine) 
env_taxa_correlation(pitlatrine, grouping_column="Country", method="pearson", pvalue.threshold=0.05,
                     padjust.method="BH", adjustment=5, num.taxa=50, select.variables=NULL)
```

**Comment by AlfredUg** [comment]
Hi @Razumall, the solution is to use `taxa.env.correlation ` instead of `taxa_env_correlation`. This change has been made in the most recent updates,  the tutorial will be updated accordingly very soon.

**Comment by Razumall** [comment]
Thx, it worked successfully.
