### ISSUE TITLE
plot_anova_diversity() - Error in names(df_pw) <- c("measure", "from", "to", "y", "p")

### ISSUE THREAD

**Issue by jud25** [umerijaz/microbiomeSeq#8]
Hi,

microbiomeSeq looks like a really interesting package. I have successfully used some nice functions as the plot_anova_diversity() which allows to have nice representations ... the first time it worked with my data (phyloseq object). Now I am trying to use it a second time, but I am having the following error message:
_"Error in names(df_pw) <- c("measure", "from", "to", "y", "p") : 
  attribut 'names' [5] doit ^etre de m^eme longueur que le vecteur [0]"_
I have checked my data but I can't figure out with what's going on... I will appreciate any help.

Thanks so much

**Comment by AlfredUg** [comment]
Heya @jud25, to get rid of this error, you may consider increasing  the threshold p-value (default is `0.05`) via the argument `pValueCutoff `. In the next updates, we shall include a suggestive message in order to avoid this error.

I hope that helps.

**Comment by jud25** [comment]
Thanks @AlfredUg,
As I understand, when I try to plot with a p-value of 0.05 and it generate that message, it means my diversity indexes are not significant... That's strange because the same function using another data matrix gives me boxplots with both significant and nonsignificant indexes. 
Thanks so much for your help !

**Comment by AlfredUg** [comment]
Hey @jud25, I am working on fixing this issue (to avoid this "**strange**" error), I will comment here as soon as I get it fixed.
Thanks

**Comment by jud25** [comment]
Nice !!!

Thanks again @AlfredUg

**Comment by russellj7** [comment]
Same issue here. Not sure what could be the issue with my data if anything.

When I adjust the p-value cutoff I then sometimes get the following message in addition to the message posted by jud25:
`Error in data.frame(x = c(which(levels(df[, grouping_column]) == as.character(df_pw[i,  : 
  arguments imply differing number of rows: 0, 2`

**Comment by AlfredUg** [comment]
@jud25 and @russellj7, this issue has been worked upon and I hope it works fine now. Kindly report anything that does not work fine still.
Thanks

**Comment by almaldon** [comment]
Hi @AlfredUg 
I am having the same issue that @russellj7 described above:
Error in data.frame(x = c(which(levels(df[, grouping_column]) == as.character(df_pw[i,  : 
  arguments imply differing number of rows: 0, 2
Thanks!

**Comment by AlfredUg** [comment]
Heya @almaldon,

Kindly post here the code generating this error.

Thanks

**Comment by AlfredUg** [comment]
Heya @almaldon,

Thanks for putting this here,  I would assume that there are only a few records for a particular level in the "disease_status"  variable.  As such, I would suggest that you try to reconstruct the metadata to include only the dominant variables (JUST TO CKECK) and then see how that works.

We shall implement a way to eliminate this and also have a warning message in case this arises in upcoming updates.

Alfred.

**Comment by almaldon** [comment]
Thank you @AlfredUg 
Unfortunately, that didn't work either. I do have another row in the metadata named: "disease", with just 2 categories: "sick" and "healthy", N = 69 and 38, respectively; and when trying to calculate ANOVA and plot I get the same error.

plot_disease <- plot_anova_diversity(t_physeq_var_depth, method = c("richness", "simpson", "shannon"), grouping_column = "disease", pValueCutoff = 0.05)

Error in data.frame(x = c(which(levels(df[, grouping_column]) == as.character(df_pw[i,  : 
  arguments imply differing number of rows: 0, 2

Thanks for the reply!
Ana

**Comment by KIRANBHATIA145** [comment]
Hi,

I am trying to run the following script:

 library (foreign)
SGA <- read.dta("U:/Kiran Bhatia/LG_ANALYSIS_101012017/LG_DATA/monitoring ana/SGA_data1.dta")
library(hbgd)
SGA$percentile_weight <- igb_wtkg2centile(SGA$ga, SGA$weight, sex=SGA$sex1)

and getting the error:

SGA$percentile_weight <- igb_wtkg2centile(SGA$GA, SGA$Weight, sex = SGA$Sex)
Error in data.frame(x = gagebrth, y = val, var = var, sex = sex, stringsAsFactors = FALSE) : 
  arguments imply differing number of rows: 0, 1

Beginners in R, don't know much about R coding. Please help to resolve my issue.

Thanks.
Kiran Bhatia
India

**Comment by Marieag** [comment]
Any news on this? It keeps letting me run the anova on my full dataset, but not on a subset of it.

**Comment by AlfredUg** [comment]
@Marieag, kindly post here the code and error generated to help us point out the issue.

Thanks

**Comment by Marieag** [comment]
@AlfredUg Sure! 

I'm getting an error like this: 

```
Error in names(df_pw) <- c("measure", "from", "to", "y", "p") : 
  'names' attribute [5] must be the same length as the vector [1]
```
When running this:

```
> p_an_p <-plot_anova_diversity(MBS_Pch, method = c("shannon", "evenness"),grouping_column ="Fungicide",pValueCutoff=0.05)+
+   theme(axis.title.x=element_blank(),
+         axis.text.x=element_blank(),
+         axis.ticks.x=element_blank()) +
+   scale_color_manual(values=set_fun)
```

I have tracked the error to something going on in `perform_anova()` itself.
This is the same error I get, if I haven't transposed the phyloseq object before using phyloseq, so I'm wondering if it's  because it somehow transposes something twice, or the dimensions end up wrong, somehow? 

I'm attaching the files from the object that's causing the error, the zip folder contains three .tsv's, one tax table, one otu table and one metadata table. These files I have created directly from the phyloseq object MBS_Pch, that causes the error. 

Would be super cool if you have time to take a look. 

[MBS_Pch.zip](https://github.com/umerijaz/microbiomeSeq/files/2623971/MBS_Pch.zip)

**Comment by Marieag** [comment]
(oh, and `set_fun <- c( "red", "violet", "brown","darkblue")` - not that it matters, but just for the sake of reproducibility)

**Comment by AlfredUg** [comment]
Thanks @Marieag,
Let me have a look at this.

**Comment by AlfredUg** [comment]
Hi @Marieag,
I have had a quick look at the dataset and I realise the error is raised by eveness ANOVA pvalues (which is non at p-value threshold 0f 0.05). We shall fix this so that plots are independent of supplied pvalues. 

Attached is the figure I generate using only Shannon. 
![marieg_shannon](https://user-images.githubusercontent.com/24940585/49210819-16bc0200-f3cf-11e8-8180-f934aa1c3bfb.png)

**Comment by AlfredUg** [comment]
Thanks for this @Marieg, I will take a look and get back to you.

Alfred Ssekagiri,

Bioinformatics Associate | H3ABioNet-UVRI node
Bioinformatics fellow | MUII-plus

________________________________

**Comment by Marieag** [comment]
Sounds good! Thanks for looking into it :) 

Cheers, Marie

**Comment by Marieag** [comment]
Sounds good! Thanks for looking into it :) 

Cheers, Marie
