### ISSUE TITLE
plot_anova_diversity: Error - Error in t.default(physeq) : argument is not a matrix

### ISSUE THREAD

**Issue by hkr01** [umerijaz/microbiomeSeq#9]
This looks like great code and I would love to start using it for some alpha and beta diversity plots.  However, after running 
`p <- plot_anova_diversity(ps_trans, method = c("richness", "simpson", "shannon"), 
                          grouping_column = "sample_Species", pValueCutoff = 0.05)`
I get the following error: `Error in t.default(physeq) : argument is not a matrix`

ps_trans is my phyloseq object 
`> ps_trans
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 1289 taxa and 25 samples ]
sample_data() Sample Data:       [ 25 samples by 2 sample variables ]
tax_table()   Taxonomy Table:    [ 1289 taxa by 7 taxonomic ranks ]`

Any help would be appreciated! Thanks!

**Comment by AlfredUg** [comment]
Heya @hkr01, this looks pretty strange and interesting at the same time. The phyloseq object looks fine. Problem would be that, for some reason, the function fails to transpose the phyloseq object. I would suggest that you try and check the orientation of the phyloseq object using `taxa_are_rows()`, after that you could transpose the phyloseq object using `ps_trans  <- t(ps_trans)` ahead of using the `plot_anova_diversity()` function. 

I hope that helps, please post back of how that goes, sorry for the late reply.

**Comment by kekokenepane** [comment]
Hi, I would just like to comment on this issue. I was using Phyloesq for some time now and connecting it with DESeq2, vegan ,.,.. And had no issues with matrix orientation. But microbiomeSeq failed at every function. Tried many things before and transposing does the trick. It works now. I'm using R 3.4.4 in windows. And seem like there are other users with similar issue. 
https://github.com/joey711/phyloseq/issues/905
Phyloseq object was constructed with import_mothur, import_qiime_sample_data and merge_phyloseq. Maybe this will help you pinpoint the issue. Thanks for nice package.
best, kekoke

**Comment by davidvilanova** [comment]
I have the same problem. Transposition did not fix it.

**Comment by Eustacialee** [comment]
Hi all,

I am facing same error "Error in t.default(physeq) : argument is not a matrix" as mentioned earlier by other user. Any other way to solve it besides using "plot_richness"? I would like to generate the similar plot_anova_diversity plot that including "Latrine categorical".

Thanks.

Regards,

**Comment by AlfredUg** [comment]
Hi @Eustacialee, kindly post here the code generating this error. 
Thanks

**Comment by javiercnav** [comment]
Hello has anyone found a solution to this issue?
"Error in t.default(physeq) : argument is not a matrix"
I tried transposing the Phyloseq object and it worked, but then If I try other parts of the tutorial I keep getting into weird issues, for example, if I try the plot_taxa, I get OTUs as my legend instead of actual taxonomic levels, which I assume also has to do with the object's orientation...
Thank you for the nice package though

**Comment by AlfredUg** [comment]
Heya @javiercnav, There is an issue with orienting phyloseq objects using microbiomeSeq functions,  The work around for this is to transpose the physeq object before calling any microbiomeseq function.
Kindly post here one of the failing examples and we shall use that to provide an example work around.

Thanks,
Alfred

**Comment by javiercnav** [comment]
Thank you for the reply @AlfredUg!,
here I go:
**First this is my phyloseq object - imported using import_biom, tree added using Ape**
>timezero.4
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 12398 taxa and 12 samples ]
sample_data() Sample Data:       [ 12 samples by 7 sample variables ]
tax_table()   Taxonomy Table:    [ 12398 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 12398 tips and 12397 internal nodes ]

> p <- plot_anova_diversity(timezero.4, method = c("richness", "simpson", "shannon"), 
+                           grouping_column = "Description", pValueCutoff = 0.05)
Error in t.default(physeq) : argument is not a matrix

> taxa_are_rows(timezero.4)
[1] TRUE

>timezero.4.trans <- t(timezero.4)
>p <- plot_anova_diversity(timezero.4.trans, method = c("richness", "simpson", "shannon"), 
                          grouping_column = "Description", pValueCutoff = 0.05)
>print(p) **#now works**
![screen shot 2018-11-21 at 10 24 49 pm](https://user-images.githubusercontent.com/8430658/48885403-fd1e2780-eddc-11e8-9a37-94dd150e5f61.png)

**then I try Plot_taxa**
physeq <- normalise_data(timezero.4.trans, norm.method = "relative")

>q <- plot_taxa(physeq, grouping_column = "Description", method = "hellinger", number.taxa = 10, 
               filename = NULL)
>print(q) 
**Here you can see that the legend doesn't bring taxonomy but OTU ID**

![screen shot 2018-11-21 at 10 25 52 pm](https://user-images.githubusercontent.com/8430658/48885539-7cabf680-eddd-11e8-9753-36242f2e292a.png)

>physeq2 <- taxa_level(timezero.4.trans, "Phylum")
>deseq_sig <- differential_abundance(physeq2, grouping_column = "Description", output_norm = "log-relative",  pvalue.threshold = 0.05, lfc.threshold = 0, filename = F)

converting counts to integer mode
Error in model.matrix.formula(design(object), colData(object)) : 
  data must be a data.frame
In addition: Warning message:
In DESeqDataSet(se, design = design, ignoreRank) :
  some variables in design formula are characters, converting to factors

**Comment by javiercnav** [comment]
Hey @AlfredUg, I found a workaround for the LCBD part,
First, my dataset is set at same taxonomic level, then normalized
>physeq_1 <- taxa_level(timezero.4.trans, "Phylum")
>physeq <- normalise_data(physeq_1, norm.method = "relative")
>q <- plot_taxa(physeq, grouping_column = "Description", method = "hellinger", number.taxa = 10, 
               filename = NULL)
>print(q)
![screen shot 2018-11-21 at 11 21 13 pm](https://user-images.githubusercontent.com/8430658/48887461-2a220880-ede4-11e8-9aa3-a6739717507c.png)

Then, I tried something similar for deseq
First created  a new transposed-phyloseq object, then set all at same taxonomic level,

>timezero.4.trans_2 <- t(timezero.4)
>physeq2 <- taxa_level(timezero.4.trans_2, "Phylum")
>deseq_sig <- differential_abundance(physeq2, grouping_column = "Description", output_norm = "log-relative", pvalue.threshold = 0.1, lfc.threshold = 0, filename = F)

converting counts to integer mode
estimating size factors
estimating dispersions
gene-wise dispersion estimates
mean-dispersion relationship
final dispersion estimates
fitting model and testing
Error in terms.formula(formula, data = data) : 
  '.' in formula and no 'data' argument
In addition: Warning message:
In DESeqDataSet(se, design = design, ignoreRank) :
  some variables in design formula are characters, converting to factors

**Seems more like a Deseq issue, and sorry for the continuous messages!**
Thanks a lot! MicrobioSeq is awesome

**Comment by AlfredUg** [comment]
Great stuff
